<a href="https://colab.research.google.com/github/suganyaudhaya/Data-science/blob/main/task_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd

In [ ]:
a=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/pollulation.zip')
print(a)

         Country                           Region  Happiness Rank  \
0    Switzerland                   Western Europe               1   
1        Iceland                   Western Europe               2   
2        Denmark                   Western Europe               3   
3         Norway                   Western Europe               4   
4         Canada                    North America               5   
..           ...                              ...             ...   
153       Rwanda               Sub-Saharan Africa             154   
154        Benin               Sub-Saharan Africa             155   
155        Syria  Middle East and Northern Africa             156   
156      Burundi               Sub-Saharan Africa             157   
157         Togo               Sub-Saharan Africa             158   

     Happiness Score  Standard Error  Economy (GDP per Capita)   Family  \
0              7.587         0.03411                   1.39651  1.34951   
1              7.561 

In [ ]:
a.mean()

<ipython-input-8-d6ac9701668a>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  a.mean()


Happiness Rank                   79.493671
Happiness Score                   5.375734
Standard Error                    0.047885
Economy (GDP per Capita)          0.846137
Family                            0.991046
Health (Life Expectancy)          0.630259
Freedom                           0.428615
Trust (Government Corruption)     0.143422
Generosity                        0.237296
Dystopia Residual                 2.098977
dtype: float64

In [ ]:
a.mode()

Country              Region  Happiness Rank  Happiness Score  \
0    Afghanistan  Sub-Saharan Africa            82.0            5.192   
1        Albania                 NaN             NaN              NaN   
2        Algeria                 NaN             NaN              NaN   
3         Angola                 NaN             NaN              NaN   
4      Argentina                 NaN             NaN              NaN   
..           ...                 ...             ...              ...   
153    Venezuela                 NaN             NaN              NaN   
154      Vietnam                 NaN             NaN              NaN   
155        Yemen                 NaN             NaN              NaN   
156       Zambia                 NaN             NaN              NaN   
157     Zimbabwe                 NaN             NaN              NaN   

     Standard Error  Economy (GDP per Capita)   Family  \
0           0.03751                   0.00000  0.00000   
1           0.03780                   0.01530  0.13995   
2           0.04394                   0.01604  0.30285   
3           0.04934                   0.06940  0.35386   
4           0.05051                   0.07120  0.38174   
..              ...                       ...      ...   
153             NaN                   1.45900  1.34043   
154             NaN                   1.52186  1.34951   
155             NaN                   1.55422  1.36058   
156             NaN                   1.56391  1.36948   
157             NaN                   1.69042  1.40223   

     Health (Life Expectancy)  Freedom  Trust (Government Corruption)  \
0                     0.92356  0.00000                        0.32524   
1                         NaN  0.07699                            NaN   
2                         NaN  0.09245                            NaN   
3                         NaN  0.10081                            NaN   
4                         NaN  0.10384                            NaN   
..                        ...      ...                            ...   
153                       NaN  0.65821                            NaN   
154                       NaN  0.65980                            NaN   
155                       NaN  0.66246                            NaN   
156                       NaN  0.66557                            NaN   
157                       NaN  0.66973                            NaN   

     Generosity  Dystopia Residual  
0       0.00000            0.32858  
1       0.00199            0.65429  
2       0.02641            0.67042  
3       0.05444            0.67108  
4       0.05547            0.89991  
..          ...                ...  
153     0.51535            3.10712  
154     0.51752            3.17728  
155     0.51912            3.19131  
156     0.57630            3.26001  
157     0.79588            3.60214  

[158 rows x 12 columns]

from matplotlib import pyplot as plt
_df_0['Happiness Rank'].plot(kind='hist', bins=20, title='Happiness Rank')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Happiness Score'].plot(kind='hist', bins=20, title='Happiness Score')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Standard Error'].plot(kind='hist', bins=20, title='Standard Error')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['Economy (GDP per Capita)'].plot(kind='hist', bins=20, title='Economy (GDP per Capita)')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('Region').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='Happiness Rank', y='Happiness Score', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='Happiness Score', y='Standard Error', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='Standard Error', y='Economy (GDP per Capita)', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8.plot(kind='scatter', x='Economy (GDP per Capita)', y='Family', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Economy (GDP per Capita)']
  ys = series['Happiness Rank']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('Economy (GDP per Capita)', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Region')):
  _plot_series(series, series_name, i)
  fig.legend(title='Region', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Economy (GDP per Capita)')
_ = plt.ylabel('Happiness Rank')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Economy (GDP per Capita)']
  ys = series['Happiness Score']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('Economy (GDP per Capita)', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Region')):
  _plot_series(series, series_name, i)
  fig.legend(title='Region', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Economy (GDP per Capita)')
_ = plt.ylabel('Happiness Score')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Economy (GDP per Capita)']
  ys = series['Standard Error']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('Economy (GDP per Capita)', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Region')):
  _plot_series(series, series_name, i)
  fig.legend(title='Region', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Economy (GDP per Capita)')
_ = plt.ylabel('Standard Error')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Economy (GDP per Capita)']
  ys = series['Health (Life Expectancy)']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_12.sort_values('Economy (GDP per Capita)', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Region')):
  _plot_series(series, series_name, i)
  fig.legend(title='Region', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Economy (GDP per Capita)')
_ = plt.ylabel('Health (Life Expectancy)')

from matplotlib import pyplot as plt
_df_13['Happiness Rank'].plot(kind='line', figsize=(8, 4), title='Happiness Rank')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_14['Happiness Score'].plot(kind='line', figsize=(8, 4), title='Happiness Score')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_15['Standard Error'].plot(kind='line', figsize=(8, 4), title='Standard Error')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_16['Economy (GDP per Capita)'].plot(kind='line', figsize=(8, 4), title='Economy (GDP per Capita)')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_17['Region'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_17, x='Happiness Rank', y='Region', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_18['Region'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_18, x='Happiness Score', y='Region', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_19['Region'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_19, x='Standard Error', y='Region', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_20['Region'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_20, x='Economy (GDP per Capita)', y='Region', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
a.std()

<ipython-input-12-7408fc62a40f>:1: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  a.std()


Happiness Rank                   45.754363
Happiness Score                   1.145010
Standard Error                    0.017146
Economy (GDP per Capita)          0.403121
Family                            0.272369
Health (Life Expectancy)          0.247078
Freedom                           0.150693
Trust (Government Corruption)     0.120034
Generosity                        0.126685
Dystopia Residual                 0.553550
dtype: float64

In [ ]:
import array as np
np=(45,67)
print(np)

(45, 67)


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
array=np.zeros(3)
print(array)

[0. 0. 0.]


In [ ]:
import numpy as np
array=np.ones(3)
print(array)

[1. 1. 1.]


In [ ]:
import numpy as np
import numpy as nd
import numpy as bb
import numpy as dd
np=np.array([5,3,8,9])
print(np)
nd=nd.arange(6)
print(nd)
bb=bb.linspace(0,5)
print(bb)
dd=dd.eye(3)
print(dd)

[5 3 8 9]
[0 1 2 3 4 5]
[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
k=np.array([[7,3,7],[6,3,0]])
g=k.shape
print(g)
h=k.ndim
print(h)
y=k.size
print(y)
f=k.dtype
print(f)

(2, 3)
2
6
int64


In [ ]:
import numpy as np
import pandas as pd
data={'FRIEND':['400 above','300_349','250-299','200-249','150-199','100-149','50-99','0-49'],
       'f':[2,5,12,17,23,49,27,29,36]}
df=pd.DataFrame(data)